# Generated by Django 4.1 on 2022-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Belum Selesai', max_length=255),
        ),
    ]
